# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: cosimo.bassi@algorand.foundation
author_name: cusma
contract_name: smart_asa
deployment_language: python
preset_name: production
project_name: arc-20

